name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.FV_ACTION }}  # 修改为使用你的secret
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
